### ISSUE TITLE
Shelly Plus 1 does not connect to WiFi after the partition manager / migration start 

### ISSUE THREAD

**Issue by ok11** [tasmota/mgos32-to-tasmota32#61]
Hey all,

observing the following: 
- after unlocking the bootloader (the restart and wifi connect was successful) and starting the migration from the partition manager, the device does not seem to connect to the wifi
- the tasmota ap is running, but 192.168.4.1 does not bring up the web ui
- http commands are accepted, but do not work properly
  - for example, `http://192.168.4.1/wi?s1=ssid&p1=pwd&save=` returns
```
File Not Found

URI: /wi
Method: GET
Arguments: 3
 s1: ssid
 p1: pwd
 save: 
```

So, the device is not bricked, but also does not run as expected. What should I do now?

T&R, Oleg
